global:
  # The default configuration for all jobs
  scrape_interval: 5s     # Set the scrape interval to 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.
  # scrape_timeout is set to the global default (10s).

# A list of scrape configurations.
scrape_configs:
  - job_name: 'spring-ai'
    # Specify the metrics path for Spring Boot's Actuator
    metrics_path: '/actuator/prometheus'
    # Override the global scrape interval for this job
    scrape_interval: 5s
    static_configs:
      # The target where the Spring AI application is running
      - targets: ['host.docker.internal:8080']